<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Catalog\Model\Layer\Filter\Item;
$jsonHelper = $this->helper(\Magento\Framework\Json\Helper\Data::class);
$layeredNavBlockName = 'catalog.leftnav';
$stateBlockName = 'catalog.navigation.state';
if($this->getRequest()->getFullActionName() === 'catalogsearch_result_index') {
    $layeredNavBlockName = 'catalogsearch.leftnav';
    $stateBlockName = 'catalogsearch.navigation.state';
} 
$layeredNavBlock =  $this->getLayout()->getBlock($layeredNavBlockName);
$stateBlock =  $this->getLayout()->getBlock($stateBlockName);
$filterViewModel = $layeredNavBlock->getViewModel();
$filterRenderer = $layeredNavBlock->getChildBlock('renderer');

// Determine active filters
$activeFilters = [];
foreach($this->getRequest()->getParams() as $key => $values) {
    $activeFilters[$key] = is_array($values) ? count($values) : 1;
}
?>

<?php if ($block->getCollection()->getSize()) : 
    $widget = $jsonHelper->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $jsonHelper->jsonEncode($widget['productListToolbarForm']);
?>
    <section id="catalog_toolbar" class="catalog-toolbar" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <div class="catalog-toolbar-top">
            <div class="catalog-toolbar-label">
                <strong><?= __('Filters'); ?></strong>
            </div>
            <div class="catalog-toolbar-actions">
                <?php if (!empty($stateBlock->getActiveFilters())) : ?>
                    <a href="<?= /* @escapeNotVerified */ $stateBlock->getClearUrl() ?>" class="clear-filters">
                        <span><?= /* @escapeNotVerified */ __('Clear All') ?></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <div class="catalog-toolbar-items">
            <!-- Layered navigation filters -->
            <?php foreach ($layeredNavBlock->getFilters() as $filter): 
                $code = $filter->getRequestVar();
                $label = $filterViewModel->getFilterTitle($filter);
            ?>
            <?php if(!$filter->getItemsCount()) continue; // Skip filters without items ?>
                <div class="toolbar-item toolbar-item--filter">
                    <div class="toolbar-item-label">
                        <strong>
                            <?= __($label); ?>
                            <?php if(isset($activeFilters[$code])): ?>
                                <span class="count">(<?= $activeFilters[$code]; ?>)</span>
                            <?php endif; ?>
                        </strong>
                    </div>
                    <div class="toolbar-item-content">
                        <?= $filterRenderer->render($filter); ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <!-- Sorter -->
            <div class="toolbar-item toolbar-item--sorter">
                <div class="toolbar-sorter">
                    <strong><?= __('Sort by'); ?>:</strong>
                    <select id="sorter" data-role="sorter">
                        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                                <?php if ($block->isOrderCurrent($_key)) :?>
                                    selected="selected"
                                <?php endif; ?>
                                >
                                <?= $block->escapeHtml(__($_order)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <?php if ($block->getCurrentDirection() == 'desc') :?>
                        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
                            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
                        </a>
                    <?php else :?>
                        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
                            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
<?php endif ?>

<script type="text/x-magento-init">
    {
        "#catalog_toolbar": {
            "catalogToolbar": {}
        }
    }
</script>