<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Framework\Escaper $escaper */

//{{block class="Magento\Framework\View\Element\Template" template="Magento_Cms::cms-account-create.phtml" title="Lorem" para="impsum"}}

$title =  ($block->getData('title') !== '') ? $block->getData('title') : __('Stay up to date');
$para = ($block->getData('para') !== '') ? $block->getData('para') : __('Subscribe to newsletter, order your creation and manage your orders. Create your account today.');
?>
<div class="cms-account-create-block" data-bind="scope: 'customer-account'">
    <div class="container" style="display: none" data-bind="visible: !customer().fullname">
        <div class="flex">
            <div class="col-12 col-md-5 text-block">
                <h2><?= $title ?></h2>
                <p><?= $para ?></p>
            </div>
            <div class="col-12 col-md-3 spacer"></div>
            <div class="col-12 col-md-4 actions">
                <a class="action primary btn-white-outline" href="<?= $block->getUrl('customer/account')?>"><span><?= __('Create your account')?></span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer-account": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
</script>


