<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
$_product = $block->getProduct();
$qtyTitle = $block->escapeHtml(__('Quantity'));
$btnTitle = $block->escapeHtml(__('Add to Cart'));
$defaultQty = $block->getProductDefaultQty() * 1;
$validate = $block->escapeHtmlAttr(json_encode($block->getQuantityValidators()));
?>
<?php if ($_product->isSaleable()) :?>
<div class="qty-cart">
    <label class="label" for="qty"><?= $qtyTitle ;?></label>
    <div class="layout">
        <div class="quantity">
            <button type="button" id="qtyDown" disabled>&#8722;</button>
            <input id="qty" name="qty" type="number" min="0" class="input-text qty"
                value="<?= $defaultQty; ?>" title="<?= $qtyTitle; ?>"  data-validate="<?= $validate; ?>" />
            <button type="button" id="qtyUp">&#43;</button>
        </div>
        <div class="actions">
            <div class="arrow-button">
                <button type="submit"
                        title="<?= $btnTitle; ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $btnTitle; ?></span>
                </button>
            </div>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
