<?php $product = $block->getProduct(); ?>
<div class="product-disclaimer">
    <p>Lorsque vous personnalisez votre bouteille ou canette, faites-le dans un esprit positif de partage. Lorsque vous personnalisez votre bouteille, faites-le dans un esprit positif de partage et en conformité avec les principes prévus dans <a href="/conditions-utilisation-site">les conditions d'utilisation</a>. Les caractères spéciaux et émoticons ne sont pas imprimables. L'utilisation de noms ou des marques déposées est sous votre responsabilité. Dans tous les cas, Coca-Cola se réserve le droit de rejeter une personnalisation après la validation de votre commande.</p>
</div>
