<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Catalog\Block\Product\View\Options */
$viewModel = $block->getData('viewModel');
$options = $block->decorateArray($block->getOptions());
$product = $block->getProduct();
$productId = $product->getId();
$productSku = $product->getSku();
$canSkus = $viewModel->getCanSkus();
$labels = $product->getSubtitle() ? explode('…', $product->getSubtitle()) : null;
?>

<?php if ($note = $product->getData('note')): ?>
    <div class="product-note-wrapper">
        <p><?= $block->escapeHtml($note); ?></p>
    </div>
<?php endif; ?>

<?php if (count($options)) :?>
    <div class="custom-options">
        <?php if($labels && $labels[0]): ?>
            <strong class="phrase-label"><?= $labels[0]; ?></strong>
        <?php endif; ?>
        <?php foreach ($options as $index => $option) : ?>
            <?php if ($index === 0) /* show first line and hide additional */ { ?>
                <div class="phrase line-<?= $index; ?>">
                    <?= $block->getOptionHtml($option) ?>
                </div>
            <?php } else { ?>
                <div class="phrase line-<?= $index; ?>" style="display:none;">
                    <?= $block->getOptionHtml($option) ?>
                </div>
            <?php } ?>
        <?php endforeach; ?>
        <?php if($labels && $labels[1]): ?>
            <strong class="phrase-label"><?= $labels[1]; ?></strong>
        <?php endif; ?>
        <div class="actions">
            <div class="add-lines">
                <?php if(count($options) > 1): ?>
                    <button id="addLine" class="add-line" type="button" aria-label="<?= __("Ajouter une autre ligne+"); ?>">
                        <span><?= __("Ajouter une autre ligne+"); ?></span>
                    </button>
                <?php endif; ?>
                <?php if(count($options) > 2): ?>
                    <button id="addToFrom" class="add-line" type="button" aria-label="<?= __("Signez la canette (optionnel)"); ?>">
                        <span><?= __("Signez la canette (optionnel)"); ?></span>
                    </button>
                <?php endif; ?>
            </div>
            <button id="showPreview" class="show-preview" type="button" aria-label="<?= __("Aperçu"); ?>">
                <span><?= __("Aperçu"); ?></span>
            </button>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "priceOptions": {
                    "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "controlContainer": ".field",
                    "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($productId) ?>'][data-role=priceBox]"
                }
            },
            "#maincontent": {
                "productPreview": {
                    "sku": "<?= $block->escapeHtml($productSku) ?>",
                    "canSkus": <?= /* @noEscape */ json_encode($canSkus) ?>
                }
            }
        }
    </script>
    <script>
        require([
            "jquery",
            "mage/mage"
        ], function($){
            var dataForm = $('#product_addtocart_form');
            dataForm.mage('validation', {
                errorPlacement: function(error, element) {
                    if (element.hasClass('phraseInput')) {
                        var parent = $(element).closest('.phrase');
                        $(parent).addClass('invalid');
                        $(parent).find('.message').html(error).show();
                    }
                }
            });
        });
    </script>
<?php endif; ?>
