<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<div class="header-account" >
    <div class="controls" data-toggle="dropdown" data-mage-init='{"dropdown":{}}' data-bind="scope: 'customer-account'">
        <span class="account-toggle"></span>
    </div>

    <ul class="header links" data-target="dropdown" data-bind="scope: 'customer-account'">
        <!-- ko if: customer().fullname  -->
        <li><a href="<?= $block->getUrl('customer/account')?>"><?= __('My Account')?></a></li>
        <li><a href="<?= $block->getUrl('sales/order/history')?>"><?= __('My Orders')?></a></li>
        <li><a href="<?= $block->getUrl('customer/account/logout')?>"><?= __('Sign Out')?></a></li>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <li><a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>><?= __('Log In')?></a></li>
        <li><a href="<?= /* @noEscape */ $block->getUrl('customer/account/create')?>"><?= __('Create an Account')?></a></li>
        <!-- /ko -->
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer-account": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
</script>


