<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper">
        <div class="data additional-attributes additional-tags">
            <?php foreach ($_additional as $_data) :?>
                <?php if ($_data['code'] === 'tags') :?>
                    <?php
                        $splitTags = explode(',', $_data['value'])
                    ?>
                    <?php foreach ($splitTags as $_tag) :?>
                        <div class="tag">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_tag, $_data['code']) ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif;?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
