stage:
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
    SEARCH_CONFIGURATION:
      _merge: true
      engine: elasticsearch
      elasticsearch_server_hostname: 'http://opensearch.internal'
      elasticsearch_server_port: '9200'
      elasticsearch_index_prefix: 'magento2'
      elasticsearch_server_timeout: '15'
  build:
    SCD_USE_BALER: false
    SCD_MAX_EXECUTION_TIME: 10800
    SCD_MATRIX:
      "Magento/blank": [ ]
      "Magento/luma": [ ]
      "Magento/backend":
        language:
          - en_US
      "Coke/global": [ ]
      "Coke/jp_marche":
        language:
          - en_US
          - ja_JP
  global:
    SCD_MATRIX:
      "Magento/blank": [ ]
      "Magento/luma": [ ]
      "Magento/backend":
        language:
          - en_US
      "Coke/global": [ ]
      "Coke/japan": [ ]
      "Coke/jp_marche":
        language:
          - en_US
          - ja_JP
