stage:
  deploy:
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
    SEARCH_CONFIGURATION:
      engine: elasticsuite
      elasticsearch7_server_hostname: '127.0.0.1'
      elasticsearch7_server_port: '9200'
      elasticsearch7_index_prefix: 'magento2_stg'
      elasticsearch7_server_timeout: '15'
  build:
    SCD_USE_BALER: false
    SCD_MAX_EXECUTION_TIME: 10800
    SCD_MATRIX:
      "Magento/blank": [ ]
      "Magento/luma": [ ]
      "Magento/backend":
        language:
          - en_US
      "Coke/global": [ ]
      "Coke/jp_marche":
        language:
          - en_US
          - ja_JP
  global:
    SCD_MATRIX:
      "Magento/blank": [ ]
      "Magento/luma": [ ]
      "Magento/backend":
        language:
          - en_US
      "Coke/global": [ ]
      "Coke/japan": [ ]
      "Coke/jp_marche":
        language:
          - en_US
          - ja_JP
