<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>
<?php if ($product->isSaleable()) :?>
    <?php if (count($options)) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
            <div class="step-header">
                <span><?= $block->getStep()?></span> <?= $block->getTitle()?>
            </div>
            <?php if($block->getSubtitle()): ?>
                <div class="step-sub-header">
                    <?= $block->getSubtitle()?>
                </div>
            <?php endif; ?>
            <?php if($block->getStep() == "2") : ?>
            <div class="custom-bundle-step2-noproduct">
                <div class="noproduct-message">
                    <span class="circlednumber">1</span><span><?= __('で容量とバンドル本数を選択すると、選択可能な商品が表示されます。') ?></span>
                </div>
            </div>
            <?php endif; ?>
            <?php if($block->getStep() == "3") : ?>
            <div class="custom-bundle-step3-nosubscription">
                <div class="noproduct-message">
                    <span class="circlednumber">2</span><span><?= __('で商品を選択すると、選択済みの商品が表示されます。') ?></span>
                </div>
            </div>
            <?php endif; ?>
            <?php foreach ($options as $option) : ?>
                <?php
                if (!$option->getSelections()) {
                    continue;
                } else {
                    echo $block->getOptionHtml($option);
                }
                ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else : ?>
        <p class="empty"><?= $block->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif;?>
