<div class="field dob required">
	<label class="label" for="dob"><span><?= $block->escapeHtml(__('Date of Birth')) ?></span></label>
	<div class="control">
		<label>
			<select name="day" id="dob-day" data-validate="{required:true}" tabindex="7">
				<?php for($i=1;$i<=31;$i++): ?>
					<?php $selected = false; ?>
					<?php if ($this->helper('Magento\Contact\Helper\Data')->getPostValue('day') == $i) $selected = ' selected'; ?>
					<option value="<?= $i ?>"<?= $selected ?>><?= str_pad($i, 2, 0, STR_PAD_LEFT) ?></option>
				<?php endfor; ?>
			</select>
			<?= $block->escapeHtml(__('Day')) ?>
		</label>
		<label>
			<select name="month" id="dob-month" data-validate="{required:true}" tabindex="8">
				<?php for($i=1;$i<=12;$i++): ?>
					<?php $selected = false; ?>
					<?php if ($this->helper('Magento\Contact\Helper\Data')->getPostValue('month') == $i) $selected = ' selected'; ?>
					<option value="<?= $i ?>"<?= $selected ?>><?= str_pad($i, 2, 0, STR_PAD_LEFT) ?></option>
				<?php endfor; ?>
			</select>
			<?= $block->escapeHtml(__('Month')) ?>
		</label>
		<label>
			<select name="year" id="dob-year" data-validate="{required:true}" tabindex="9">
				<?php $curYear = date('Y'); $endYear = $curYear-100; for($i=$curYear;$i>=$endYear;$i--): ?>
					<?php $selected = false; ?>
					<?php if ($this->helper('Magento\Contact\Helper\Data')->getPostValue('year') == $i) $selected = ' selected'; ?>
					<option value="<?= $i ?>"<?= $selected ?>><?= $i ?></option>
				<?php endfor; ?>
			</select>
			<?= $block->escapeHtml(__('Year')) ?>
		</label>
	</div>
</div>
<script>
    require([
        'jquery',
        'domReady!'
    ], function (jQuery) {

        jQuery('#dob-year, #dob-month').on('change', function () {
            fillDaysOfMonth();
        });

        function getDaysInMonth(month, year) {
            var date = new Date(year, month, 1);
            var days = [];
            while (date.getMonth() === month) {
                days.push(new Date(date));
                date.setDate(date.getDate() + 1);
            }
            return days;
        }

        function fillDaysOfMonth() {
            var day = jQuery('#dob-day'),
                dayVal = day.val(),
                monthVal = parseInt(jQuery('#dob-month').val()-1),
                yearVal = parseInt(jQuery('#dob-year').val()),
                daysInMonth = getDaysInMonth(monthVal, yearVal),
                daysInMonthLength = daysInMonth.length,
                selected;

            if (day.find('option').length !== daysInMonthLength) {
                day.empty();
                for (i = 1; i <= daysInMonthLength; i++) {
                    day.append(jQuery('<option/>', {'value': i, 'text': String('00' + (i)).slice(-2)}));
                }
                day.val(dayVal);
            }
        }
    });
</script>
