<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php

/** @var $viewModel CokeJapan\Checkout\ViewModel\CartCustom */
/** @var $block Magento\Checkout\Block\Cart */

$viewModel = $block->getViewModel();

?>
<?php if ($viewModel->isLoggedIn()) : ?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $(document).ready(function () {
                $('div.cart-login-container').css('display','none');
            })
        });
    </script>
<?php else : ?>
    <div class="primary">
        <button type="submit" class="action login primary" name="send" id="send2">
            <span><?= $viewModel->escapeHtml(__('Sign In')) ?></span>
        </button>
    </div>
<?php endif; ?>
