<section class="custom-bottles">
    <div class="layout">
        <div class="image">
            <img src="<?= $this->getViewFileUrl('images/custom-bottles.png'); ?>" alt="<?= __("À vous de jouer"); ?>" />
        </div>
        <div class="form">
            <div class="title">
                <strong><?= __("À vous de jouer"); ?></strong>
            </div>
            <form id="custom-bottle-form">
                <input id="custom-bottle-input" type="text" placeholder="<?= __("Saisissez jusqu’à 18 caractères"); ?>" maxlength="18" required />
                <button type="submit"><?= __("Personnaliser"); ?></button>
            </form>
        </div>
    </div>
</section>

<script>
    require([
        'jquery',
    ], function ($) {
        function encodeParams(str) {
            return encodeURIComponent(str).replace(/!/g, '%21');
        }
        $(function () {
            $(document).on('submit','#custom-bottle-form',function(e){
                e.preventDefault();
                var value = $('#custom-bottle-input').val();
                window.location = '/bouteille-personnalisee.html?line1=' + encodeParams(value);
            });
        });
    });
</script>