<div class="wrapper">
    <div class="layout">
        <div class="column-login">
            <div class="above-form">
                <div class="above-form-image">
                    <img src="/media/wysiwyg/happy-healthy_opt.png" />
                </div>
                <div class="above-form-headline">
                    <h1><?= __('Elder Concierge Project'); ?></h1>
                </div>
            </div>
            <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post"
                id="login-form" data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset login"
                    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                                <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?>
                                id="email" type="email" class="input-text"
                                title="<?= $block->escapeHtmlAttr(__('Email')) ?>" placeholder="<?= __("Email Address"); ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password"
                                <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?>
                                class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                placeholder="<?= __("Password"); ?>" data-validate="{required:true}">
                        </div>
                    </div>
                    <div class="forgot-password">
                        <a href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                            <?= $block->escapeHtml(__('Forgot Your Password?')) ?>
                        </a>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="primary"><button type="submit" class="action login primary" name="send"
                                id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button></div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="column-helpers">
            <img src="/media/wysiwyg/homepage-helpers_opt.png" />
        </div>
    </div>
</div>
