<?php
/**
 * @see \Magento\Framework\View\Element\Html\Calendar
 */
?>

<script>
    require([
        'jquery',
        'jquery-ui-modules/datepicker'
    ], function($){
        $.extend(true, $, {
            calendarConfig: {
                dayNames: <?= /* @noEscape */ $days['wide'] ?>,
                dayNamesMin: <?= /* @noEscape */ $days['abbreviated'] ?>,
                monthNames: <?= /* @noEscape */ $months['wide'] ?>,
                monthNamesShort: <?= /* @noEscape */ $months['abbreviated'] ?>,
                dateFormat: $.datepicker.RFC_2822
            }
        });
    });
</script>
