<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<nav class="footer-links">
    <ul>
        <li><a href="#"><?= $block->escapeHtml(__('Terms of Use')) ?></a></li>
        <li><a href="#"><?= $block->escapeHtml(__('Cookie Policy')) ?></a></li>
        <li><a href="#"><?= $block->escapeHtml(__('Privacy Policy')) ?></a></li>
        <li><a href="#"><?= $block->escapeHtml(__('Contact Us')) ?></a></li>
        <li><a href="#"><?= $block->escapeHtml(__('FAQ')) ?></a></li>
    </ul>
</nav>
