<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>


<ul class="social-icons">
    <li>
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/icons/icon-facebook.svg') ?>" alt="Facebook" />
        </a>
    </li>
    <li>
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/icons/icon-twitter.svg') ?>" alt="Twitter" />
        </a>
    </li>
    <li>
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/icons/icon-instagram.svg') ?>" alt="Instagram" />
        </a>
    </li>
</ul>
