<?php
/**
 * phpcs:disable Magento2.Templates.ThisInTemplate
 * @var \Magento\Customer\Helper\Address $addressHelper
 * @var \FortyFour\ShippingAddressRestriction\ViewModel\Customer\Address $viewModel
 */

$addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);
$requiredAttributesPrechecked = $block->getData('required_attributes_prechecked');
$viewModel = $block->getViewModel();
?>
<form class="form-address-edit" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
        <?= $block->getNameBlockHtml() ?>
        <?php if ($addressHelper->isAttributeVisible('company')) : ?>
            <div class="field company <?php if (in_array('company', $requiredAttributesPrechecked)) :
                ?>required<?php endif; ?>">
                <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="input-text <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('company')) ?>"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($addressHelper->isAttributeVisible('telephone')) : ?>
            <div class="field telephone <?php if (in_array('telephone', $requiredAttributesPrechecked)) :
                ?>required<?php endif; ?>">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="text" name="telephone" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('telephone') ?>" id="telephone" minlength="11"/>
                </div>
                <div class="note">
                    <span><?= __("We only accept valid mobile numbers. Landline numbers cannot be accepted."); ?></span>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($addressHelper->isAttributeVisible('fax')) : ?>
            <div class="field fax">
                <label class="label" for="fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
                <div class="control">
                    <input type="text" name="fax" id="fax" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('fax') ?>"/>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>

    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>

        <?php if ($viewModel->isShippingAddressRestrictionEnabled()): ?>
            <div class="field address-type checkbox">
                <label class="label" for="billing-address-toggle">
                    <span><?= $block->escapeHtml(__('This address is a billing address.')) ?></span>
                </label>
                <div class="control">
                    <input type="checkbox" id="billing-address-toggle" name="billing_address_toggle" />
                </div>
            </div>
        <?php endif; ?>

        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                <div class="nested">
                    <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++) : 
                        $label = $block->escapeHtml(__('Street Address %1', $_i));
                        if($_i === 2) $label = __("Building Number");
                        if($_i === 3) $label = __("Apartment Number");
                        ?>
                        <div class="field additional required">
                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?= $label; ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[<?= $_i; ?>]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text required-entry"/>
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($addressHelper->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id') ?>" id="vat_id"/>
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required" data-bind="scope: 'shipping_address_restriction_city'">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">

                <?php if ($viewModel->isShippingAddressRestrictionEnabled()): ?>
                    <!-- ko template: getTemplate() --><!-- /ko -->
                <?php else: ?>
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>" id="city"/>
                <?php endif; ?>

            </div>
        </div>
        <div class="field region required" data-bind="scope: 'shipping_address_restriction_region'">
            <label class="label" for="region_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
            <div class="control">

                <?php if ($viewModel->isShippingAddressRestrictionEnabled() && $viewModel->canApplyToRegion()): ?>
                    <!-- ko template: getTemplate() --><!-- /ko -->
                <?php else: ?>
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
                <?php endif; ?>

            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
            <div class="control">
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>"/>
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
        <?php if ($userDefinedAttributes) :?>
            <?= $userDefinedAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif;?>
        <?php if ($block->isDefaultBilling()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox"/>
                <label class="label" for="primary_billing"><span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox"/>
                <label class="label" for="primary_shipping"><span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1"/>
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" data-action="save-address" title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<!-- Add input mask to telephone -->
<script type="text/javascript">
require(['jquery','inputmask'], function($){
    $('input[name="telephone"]').inputmask('99999999999');
})
</script>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

<?php if ($viewModel->isShippingAddressRestrictionEnabled()): ?>

    <?php if ($viewModel->canApplyToRegion()): ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components" : {
                            "shipping_address_restriction_city": {
                                "component": "FortyFour_ShippingAddressRestriction/js/view/customer/address/edit/city",
                                "city": "<?= $block->escapeHtml($block->getAddress()->getCity()) ?>",
                                "title": "<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                            },
                            "shipping_address_restriction_region": {
                                "component": "FortyFour_ShippingAddressRestriction/js/view/customer/address/edit/region",
                                "region": "<?= $block->escapeHtml($block->getRegion()) ?>",
                                "title": "<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>",
                                "cityRegistryPath": "shipping_address_restriction_city"
                            }
                        }
                    }
                }
            }
        </script>
    <?php else: ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components" : {
                            "shipping_address_restriction_city": {
                                "component": "FortyFour_ShippingAddressRestriction/js/view/customer/address/edit/city",
                                "city": "<?= $block->escapeHtml($block->getAddress()->getCity()) ?>",
                                "title": "<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                            }
                        }
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
