<?php if($customInvoiceNumber = $block->getCustomInvoiceNumber()):?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Custom Invoice Number') ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php echo nl2br($block->escapeHtml($customInvoiceNumber));?>
        </div>
    </section>
<?php endif; ?>
