<?php
// @codingStandardsIgnoreFile
?>
<div class="block block-customer-form block-customer-forgotten-pw">
    <p><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')); ?></p>
    <div id='cds-forgot-password-form' class="cds-form"></div>
</div>

<script type="text/x-magento-init">
    {
        "#cds-forgot-password-form": {
            "Coke_Cds/js/pages/forgot-password": {
                "forgotPasswordId": "cds-forgot-password-form"
            }
        }
    }
</script>
