<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var \Magento\Customer\Block\Form\Register $block
 */
?>

<div class="block block-customer-form block-account-create">
    <div id='ces-social-login-form' class="cds-form"></div>
    <div id='cds-merge-account' class="cds-form"></div>
    <div id='cds-post-login' class="cds-form"></div>
    <div id="ces-register-form" class="cds-form form create account"></div>
    <div id="ces-register-merge-form" class="cds-form"></div>
</div>
<script type="text/x-magento-init">
    {
        "#ces-register-form": {
            "Coke_Cds/js/pages/register": {
                "registerFormId": "ces-register-form",
                "registerMergeFormId": "ces-register-merge-form",
                "socialLoginId": "ces-social-login-form",
                "mergeAccountId": "cds-merge-account",
                "postLoginId": "cds-post-login"
            }
        }
    }
</script>
