<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$_product = $block->getProduct();

// is katy perry product
$kpSkus = array(
    'GB-EN-STD330-KP-CZ',
    'GE-GE-SLK330-KP-CZ',
    'NL-NL-STD330-KP-CZ',
    'BE-DU-STD330-KP-CZ',
    'BE-FR-STD330-KP-CZ',
    'NW-NW-SLM250-KP-CZ',
    'IE-EN-SLK330-KP-CZ'
);
$isKp = in_array($_product->getSku(), $kpSkus);

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
?>

<div class="img-wrap">
    <img src="<?= /* @noEscape */ $mainImageData; ?>" alt="main product photo" />
    <?php if($isKp): ?>
        <div class="overlays">
            <img class="limited-edition-badge" src="<?php echo $block->getViewFileUrl('images/limited-edition.svg') ?>" alt="Limited Edition" />
            <img
                class="katy-perry-logo _hide-sm-up"
                srcset="<?php echo $block->getViewFileUrl('images/katy-perry-resolution@2x.png') ?> 2x,
                        <?php echo $block->getViewFileUrl('images/katy-perry-resolution.png') ?> 1x"
                src="<?php echo $block->getViewFileUrl('images/katy-perry-resolution.png') ?>"
                alt="Katy Perry"
            />
        </div>
    <?php endif; ?>
</div>
