<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div class="pdp-txt-details kp-txt-details">
    <section>
        <div class="spotlight-img"></div>
        <h4 class="title">Katy commenting on the Limited-Edition can</h4>
        <p>I’m delighted to be able to support the amazing work ONE does around the world with the proceeds from the sale of my limited-edition Coca-Cola can featuring my personal resolution “I Promise to Meditate.” ✨♥️</p>
        <p>For me, the theme of 2020 was “resilience.” I’m sure I’ll need to carry that into 2021 as well, but now that we’ve entered a new year, I am going to continue to be ‘Open To Better’.</p>
        <p>This year, I promised myself I would meditate more. Transcendental Meditation has profoundly changed my life for the past 10 years and for me, being ‘Open To Better’ means being open to changing the small things that can help you improve your mind, body and spirit and connecting better with the world around you.</p>
    </section>
    <section>
        <img class="one-logo" src="<?php echo $block->getViewFileUrl('images/one-logo.svg') ?>" alt="one" />
        <p><strong>Gayle Smith, President and CEO of the ONE Campaign added:</strong><br />“Encouraging and inspiring young people during these challenging times couldn’t be more important and we are excited to be part of Coca-Cola’s Open ‘To Better’ campaign with Katy Perry. At ONE we have the privilege of working with young activists all over the world, including across Europe, who use their voices to campaign for a world without extreme poverty and preventable disease. We’re honoured that our work will be supported by the proceeds of this limited edition can.”</p>
    </section>
    <section>
        <p><strong>one.org/open-to-better</strong></p>
        <p class="_text-color-light">Each can will cost £5.00 or €5.00, which includes postage and packaging in the participating country.</p>
    </section>
</div>
