<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div class="kp-title">
    <h1>
        <img
            srcset="<?php echo $block->getViewFileUrl('images/katy-perry-resolution-2@2x.png') ?> 2x,
                    <?php echo $block->getViewFileUrl('images/katy-perry-resolution-2.png') ?> 1x"
            src="<?php echo $block->getViewFileUrl('images/katy-perry-resolution-2.png') ?>"
            alt="Katy Perry"
        />
        <img src="<?php echo $block->getViewFileUrl('images/one-logo.svg') ?>" alt="One" />
    </h1>
</div>
