<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$viewModel = $block->getViewModel();
?>

<div data-bind="scope: 'addressSuggestions'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "autocomplete": {
                        "component": "CokeEurope_AddressAutocomplete/js/autocomplete"
                    },
                    "addressSuggestions": {
                        "component": "CokeEurope_AddressAutocomplete/js/view/address-suggestions",
                        "config": <?= $viewModel->getJsonConfig(); ?>
                    }
                }
            }
        }
    }
</script>
