<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel CokeEurope\PersonalizedProduct\ViewModel\Product\Personalization
 */
$viewModel = $block->getViewModel();
?>
<script type="text/javascript">
    (function () {
        if (!("fonts" in document)) return;
        <?php foreach($viewModel->getAvailableFonts() as $font): ?>
            document.fonts.load("<?= $font; ?>");
        <?php endforeach; ?>
    })();
</script>