<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * Dynamic product attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
$product = $block->getProduct();
$attributes = $block->getAdditionalData();
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>

<section class="dynamic-attributes">
    <!-- Description -->
    <?php if($product->getDescription()): ?>
        <div class="dynamic-attribute active" data-attribute-content="description">
            <div class="attribute-title">
                <strong><?= __("Description"); ?></strong>
            </div>
            <div class="attribute-content">
                <?= $product->getDescription(); ?>
            </div>
        </div>
    <?php endif; ?>
    <!-- Additional attributes -->
    <?php if($attributes): ?>
        <?php foreach($attributes as $attribute): ?>
            <div class="dynamic-attribute" data-attribute-content="<?= $attribute['code']; ?>">
                <div class="attribute-title">
                    <strong><?= $block->escapeHtml($attribute['label']); ?></strong>
                </div>
                <div class="attribute-content">
                    <?= /* @noEscape */ $helper->productAttribute($product, $attribute['value'], $attribute['code']); ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- Shipment & Returns (CMS BLOCK) -->
    <?php if($shipBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipment_returns')->toHtml()): ?>
        <div class="dynamic-attribute">
            <div class="attribute-title">
                <strong><?= __("Shipment & Returns"); ?></strong>
            </div>
            <div class="attribute-content">
                <?= $shipBlock; ?>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>
require([
    'jquery',
], function ($) {
    $(function () {
        $( ".dynamic-attribute" ).click(function() {
            $(this).toggleClass("active");
        });
    });
});
</script>
