<?php
// @codingStandardsIgnoreFile
?>
<div id='cds-forgot-password-form' class="cds-form">
    <div class="field note">
        <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')); ?>
    </div>
</div>

<span class="required-fields-label"><?= $block->escapeHtml(__('* Required Fields')) ?></span>

<div class='actions-toolbar'>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">
            <span><?= $block->escapeHtml(__('Go back')) ?></span>
        </a>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#cds-forgot-password-form": {
            "Coke_Cds/js/pages/forgot-password": {
                "forgotPasswordId": "cds-forgot-password-form",
                "emailAddress": "<?= $block->escapeJs($this->getRequest()->getParam('email')); ?>"
            }
        }
    }
</script>
