<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?></p>
            <ul>
                <li><?= $block->escapeHtml(__('You can earn points that can be used at My Coke Store.')) ?></li>
                <li><?= $block->escapeHtml(__('You will be able to purchase a subscription.')) ?></li>
                <li><?= $block->escapeHtml(__('We will send you information on special campaigns by e-mail.')) ?></li>
                <li><?= $block->escapeHtml(__('You can store your credit card securely, which will make your second and subsequent orders smoother.')) ?></li>
            </ul>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
