<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
$datalayer = $block->getDatalayerConfig();
if ($datalayer) {
    $map = $datalayer->getDatalayerProductMap();
}
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php $items = $block->getProductCollection()->getItems(); ?>
    <div class="block widget personalized-product-list">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="products-list">
                <ol class="product-items personalized">
                    <?php $i = 0; // iterator for datalayer position ?>
                    <?php  foreach ($items as $product): 
                        $i++;
                        $renderer = $block->getDetailsRenderer('product_card');
                        $renderer->setProduct($product);
                        $renderer->setListBlock($block);
                        if($datalayer) {
                            $renderer->setDatalayer($datalayer->getProductData($product, $map, $i));
                        }
                    ?>
                        <li class="grid-item">
                            <?= $renderer->toHtml(); ?>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
