<?php
/* @var $block \Aheadworks\Sarp2\Block\Customer\Subscriptions\Edit\Address */
/* @var $billingAddressViewModel \Coke\Sarp2\ViewModel\BillingAddress */

// @codingStandardsIgnoreFile
?>
<?php
$billingAddressViewModel = $block->getBillingAddressViewModel();
$profile = $block->getProfile();
$shippingAddress = $profile->getShippingAddress();
$newAddressTitle = __('+ New Address');
$saveAddressTitle = __('Save Address');
?>
<div class="aw-sarp2__address-form">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Current Address')) ?></span>
        </legend>
        <div class="aw-sarp2__current-address">
            <?php if ($shippingAddress): ?>
                <?= /* @noEscape */ $block->getFormattedAddress($shippingAddress) ?>
            <?php else: ?>
                <?= /* @noEscape */ $block->escapeHtml(__('Not Selected')) ?>
            <?php endif; ?>
        </div>
    </fieldset>
    <form class="form validate"
          action="<?= $block->escapeUrl($block->getSaveUrl($profile->getProfileId())) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="field customer-address required">
                <select id="customer_address_id"
                        title="<?= $block->escapeHtml(__('Customer Address')) ?>"
                        name="customer_address_id"
                        class="validate-select">
                    <?php foreach ($block->getCustomerAddress() as $addressId => $address): ?>
                        <option value="<?= /* @noEscape */ $addressId ? : '' ?>">
                            <?= $block->escapeHtml($address) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <button type="submit"
                    class="action primary"
                    title="<?= $block->escapeHtml($saveAddressTitle) ?>">
                <span><?= $block->escapeHtml($saveAddressTitle) ?></span>
            </button>
        </fieldset>
    </form>
</div>
<div class="actions-toolbar">
    <button data-role="aw-sarp2-add-address"
            type="button"
            class="action secondary"
            title="<?= $block->escapeHtml($newAddressTitle) ?>">
        <span><?= $block->escapeHtml($newAddressTitle) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
{
    "[data-role=aw-sarp2-add-address]": {
        "awSarp2ButtonControl": {
            "newLocation": <?php /* @noEscape */ echo $block->jsonEncode($billingAddressViewModel->getAddAddressUrl()) ?>
        }
    }
}
</script>
