<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
/** @var \Magento\Framework\Escaper $escaper */


$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<div class="header-account-wrapper" data-bind="scope: 'customer-account'">
    <div class="controls">
        <a href="<?= $block->getUrl('customer/account')?>">
            <span class="account-icon"></span>
            <!-- ko if: customer().fullname  -->
            <span class="logged-in">
                <span data-bind="text: new String('<?= $escaper->escapeHtml(__('Welcome')) ?>')"></span>
                <span data-bind="text: new String('<?= $escaper->escapeHtml(__('%1 樣', '%1')) ?>').replace('%1', customer().fullname)"></span>
            </span>
            <!-- /ko -->
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer-account": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
</script>


