<div data-block="minicart" class="mini-cart item">
    <a class="action showcart _hide-md-dwn" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
       <div class="icon-wrap" data-bind="css: { showcart: !!getCartParam('summary_count') == false}" >
            <svg viewBox="0 0 16 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M1 7.18192V14.9091C1 16.616 2.35323 18 4.0223 18H11.578C13.2471 18 14.6003 16.616 14.6003 14.9091V7.18192H1Z" stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M4.02246 9.49991V4.86359C4.02246 2.72934 5.71344 1 7.80033 1C9.88723 1 11.5782 2.72934 11.5782 4.86359V9.49991" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <!-- ko if: getCartParam('summary_count') -->
            <span class="counter qty"
                data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            </span>
            <!-- /ko -->
        </div>
    </a>

    <a class="action _hide-md-up" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
       <div class="icon-wrap">
            <svg viewBox="0 0 16 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M1 7.18192V14.9091C1 16.616 2.35323 18 4.0223 18H11.578C13.2471 18 14.6003 16.616 14.6003 14.9091V7.18192H1Z" stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M4.02246 9.49991V4.86359C4.02246 2.72934 5.71344 1 7.80033 1C9.88723 1 11.5782 2.72934 11.5782 4.86359V9.49991" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <!-- ko if: getCartParam('summary_count') -->
            <span class="counter qty"
                data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            </span>
            <!-- /ko -->
        </div>
    </a>

    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart _hide-md-dwn"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function($) {
                $('a.action.showcart').click(function(e) {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
