<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<header id="site-header" class="coke-header">
    <div class="container">
        <div class="layout">
            <div class="column left">
                <div class="header-nav-toggle">
                    <span data-action="toggle-nav" class="action nav-toggle"><span><?= __('Basculer la navigation'); ?></span></span>
                </div>
                <div class="header-logo">
                    <a href="/">
                        <img src="<?= $this->getViewFileUrl('images/coke-store-logo.png'); ?>" />
                    </a>
                </div>
                <div class="header-nav">
                    <?php if ($this->getChildHtml('site-navigation')) : ?>
                        <?= $this->getChildHtml('site-navigation'); ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="column right">
                <div class="header-search">
                    <?= $this->getBlockHtml('top.search'); ?>
                </div>
                <div class="header-customer">
                    <a href="/customer/account/" class="action account"></a>
                </div>
                <div class="header-cart">
                    <?= $this->getBlockHtml('minicart'); ?>
                </div>
            </div>
        </div>
    </div>
    <?php if ($this->getChildHtml('site-navigation-dropdown')) : ?>
        <?= $this->getChildHtml('site-navigation-dropdown'); ?>
    <?php endif; ?>
</header>
