<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div class="country-selector">
    <a href="#">
        <span class="icon">
            <div class="flag">
                <img src="<?php echo $block->getViewFileUrl('images/flags/GB@3x.png') ?>" alt="UK" />
            </div>
        </span>
        <span class="title"><?= $block->escapeHtml(__('UK')) ?></span>
    </a>
</div>
