<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Coke\OLNB\ViewModel\LanguageChanger $viewModel */
$viewModel = $block->getViewModel();

$currentStoreId = $viewModel->getCurrentStoreId();
$stores = $viewModel->getLocales();
?>
<div class="country-selector">
    <?php foreach ($stores as $locale => $store): ?>
    <a href="<?= $viewModel->getTargetStoreRedirectUrl($store); ?>" <?php if ($store->getId() === $currentStoreId): ?>class="current-store"<?php endif; ?>>
        <span class="title">
            <?= $block->escapeHtml(__('%1', $store->getName())) ?>
            <i class="ion ion-ios-arrow-round-forward"></i>
        </span>
    </a>
    <?php endforeach; ?>
</div>
