<?php
/**
 * @var $block \Coke\Bundle\Block\Navigation\CustomBundle
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"collapsible": true, "active": false}}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */ $filtered ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>

        <div class="block-actions filter-actions">
            <span class="action clear filter-clear"><?= __('Clear All') ?></span>
        </div>

        <div class="block-content filter-content"
             data-mage-init='{"Smile_ElasticsuiteCatalog/js/modal-filter-mobile":{}}'>
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */ __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"collapsible": true}}'>
                            <?php $wrapOptions = true;?>
                    <?php endif; ?>
                    <div data-role="collapsible" class="filter-options-item" data-filter="<?= /** @noEscape  */ $filter->getName() ?>">
                        <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */ __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#layered-filter-block": {
            "Coke_Bundle/js/layered-navigation": {
                "filterDrillDown": "<?= /** @noEscape  */ $block->getFilterDrillDown() ?>"
            }
        }
    }
</script>
