<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img
    <?php foreach ($block->getCustomAttributes() as $attribute) : ?>
        <?=  $block->escapeHtmlAttr($attribute) ?>
    <?php endforeach ?>
  src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
  alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"
/>
