<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div class="resolution-wrapper">
    <header>
        <?php echo $block->getChildHtml('page.main.title'); ?>
        <p class="page-subtitle _hide-md _hide-lg _hide-xlg _text-color-light"><?= $block->escapeHtml(__('Share it with a loved one')) ?></p>
    </header>
    <?php echo $block->getChildHtml('list-products'); ?>
</div>

