<?php
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);

/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Catalog\Model\Product $_product */
$_product = $block->getProduct();

// is katy perry product
$kpSkus = array(
    'GB-EN-STD330-KP-CZ',
    'GE-GE-SLK330-KP-CZ',
    'NL-NL-STD330-KP-CZ',
    'BE-DU-STD330-KP-CZ',
    'BE-FR-STD330-KP-CZ',
    'NW-NW-SLM250-KP-CZ',
    'IE-EN-SLK330-KP-CZ',
    'NI-EN-STD330-KP-CZ',
);
$isKp = in_array($_product->getSku(), $kpSkus)
?>

<div class="pdp-wrapper<?php if($isKp): ?> _katy-perry-pdp<?php endif; ?>">
    <div id="pdpMediaContainer" class="pdp-media">
        <?php echo $block->getChildHtml('product.info.media.image'); ?>
        <?php if($isKp): ?>
            <div class="_hide-xs _hide-xxs">
                <?php echo $block->getChildHtml('kp.details'); ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="pdp-details">
        <?php echo $block->getChildHtml('messages'); ?>
        <?php if($isKp): ?>
            <?php echo $block->getChildHtml('kp.title'); ?>
        <?php else: ?>
            <p><?= $block->escapeHtml(__('Now customize your resolution')) ?></p>
        <?php endif; ?>
        <?php echo $block->getChildHtml('product.info.main'); ?>
        <?php if($isKp): ?>
            <div class="_hide-sm-up">
                <?php echo $block->getChildHtml('kp.details'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>
require([
    'jquery',
    'domReady!'
], function ($) {
    const imageContainer = $('#pdpMediaContainer');
    const headerContainer = $('#site-header');

    function handleImgScrolled() {
        if ($(this).scrollTop() > 0) {
            imageContainer.addClass('small-img');
        } else {
            imageContainer.removeClass('small-img');
        }
    }

    imageContainer.css({ top: headerContainer[0].getBoundingClientRect().height });
    handleImgScrolled();

    $(window).on('resize scroll orientationchange', function(e) {
        imageContainer.css({ top: headerContainer[0].getBoundingClientRect().height });
        handleImgScrolled();
    });
});
</script>
