<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <?php foreach ($block->getStores() as $_lang) : ?>
            <span class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                    <?= __($block->escapeHtml($_lang->getName())) ?>
                </a>
            </span>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
