<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Files.LineLength
// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/**
 * @see \Magento\Reward\Block\Tooltip
 * @var \Magento\Reward\Block\Tooltip $block
 */
?>
<div class="message info reward <?= $block->escapeHtmlAttr($block->getWrapperClass()) ?>">
    <?php if ($block->hasRewardMessage()) : ?>
        <span><?= $block->escapeHtml(__($block->getRewardMessage(), $this->helper(\Magento\Reward\Helper\Data::class)->formatReward($block->getRewardPoints(), $block->getRewardAmount(), null, '<strong>%s</strong>')), ['strong']) ?></span>
    <?php endif;?>
    <?php if ($block->hasQtyLimit() && $block->hasRewardQtyLimitationMessage()) : ?>
        <span class="reward-limit"><?= $block->escapeHtml(__($block->getRewardQtyLimitationMessage(), "<strong>{$block->getQtyLimit()}</strong>"), ['strong']) ?></span>
    <?php endif;?>
    <?php if ($block->hasGuestNote()) : ?>
        <span class="reward-limit"><?= $block->escapeHtml(__($block->getGuestNote())) ?></span>
    <?php endif;?>
</div>
