http://{all}/:
  type: upstream
  upstream: mymagento:php
https://{all}/:
  type: upstream
  upstream: mymagento:php
http://{default}/:
  type: upstream
  upstream: mymagento:php
https://{default}/:
  type: upstream
  upstream: mymagento:php
