<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tr class="item-info">
    <td class="col img">
        <?php if ($block->hasProductUrl()) :?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                tabindex="-1"
                class="product-item-photo">
        <?php else :?>
            <span class="product-item-photo">
        <?php endif;?>
        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        <?php if ($block->hasProductUrl()) :?>
            </a>
        <?php else :?>
            </span>
        <?php endif; ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
                <ul class="item-options">
                    <?php foreach ($_options as $_option) :?>
                        <li>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <span class="label"><?= $block->escapeHtml($_option['label']) ?></span>
                            <span class="value">
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>

        <div class="product-mobile-details">
            <div class="total">
                <?= $block->getRowTotalHtml($_item) ?> <span class="qty">(x<?= $block->escapeHtmlAttr($block->getQty()) ?>)</span>
            </div>
            <div class="foot-row">
                <div class="qty-toggler cart-row">
                    <div class="control">
                        <button type="button" class="button btn-number" data-type="minus" data-field="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">-</button>
                        <div class="qty-wrap">
                            <input
                                id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                data-old-value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                type="text"
                                step="any"
                                min="0"
                                max="99999"
                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty qty-input"
                                data-validate="{required:true,'validate-greater-than-zero':true}"
                                data-role="cart-item-qty"
                                readonly
                            />
                        </div>
                        <button type="button" class="button btn-number" data-type="plus" data-field="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">+</button>
                    </div>
                    <div class="update-cart-qty-action" data-update="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">
                        <button type="submit"
                                name="update_cart_action"
                                data-cart-item-update=""
                                value="update_qty"
                                title="<?= $block->escapeHtmlAttr(__('Update')) ?>"
                                class="action update">
                            <span><?= $block->escapeHtml(__('Update')) ?></span>
                        </button>
                    </div>
                </div>
                <div class="item-actions">
                    <?= /* @noEscape */ $block->getActions($_item) ?>
                </div>
            </div>
        </div>
    </td>

    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map"
                    id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                    data-mage-init='{"addToCart":{
                                        "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                        "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                        "showAddToCart": false
                                        }
                                    }'
                >
                    <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                </a>
            </span>
        </td>
    <?php else :?>
        <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <div class="qty-toggler cart-row">
            <div class="control">
                <button type="button" class="button btn-number" data-type="minus" data-field="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">-</button>
                <div class="qty-wrap">
                    <input
                        id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                        name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                        data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                        data-old-value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                        value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                        type="text"
                        step="any"
                        min="0"
                        max="99999"
                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                        class="input-text qty qty-input"
                        data-validate="{required:true,'validate-greater-than-zero':true}"
                        data-role="cart-item-qty"
                        readonly
                    />
                </div>
                <button type="button" class="button btn-number" data-type="plus" data-field="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">+</button>
            </div>

            <div class="update-cart-qty-action" data-update="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]">
                <button type="submit"
                        name="update_cart_action"
                        data-cart-item-update=""
                        value="update_qty"
                        title="<?= $block->escapeHtmlAttr(__('Update')) ?>"
                        class="action update">
                    <span><?= $block->escapeHtml(__('Update')) ?></span>
                </button>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
        
        <div class="item-actions">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
