<div class="cj-footer-content">
    <div class="wrapper">
        <nav class="cj-footer-nav">
            <ul>
                <li>
                    <a href="#service">
                        <span>自宅で元気応援サービスについて</span>
                    </a>
                </li>
                <li>
                    <a href="https://www.cocacola.co.jp/company-information">
                        <span>企業情報</span>
                    </a>
                </li>
                <li>
                    <a href="https://www.cocacola.co.jp/company-information/privacy-policy">
                        <span>プライバシーポリシー</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="cj-footer-copyright">
            <p>Copyright &copy; Coca-Cola (Japan) Company, Limited</p>
        </div>
    </div>
</div>