<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \CokeEurope\Checkout\ViewModel\Success\Additional
 */
$viewModel = $block->getViewModel();
$order = $viewModel->getOrder();
$items = $order->getAllVisibleItems();
?>

<ol class="products-ordered">
    <?php foreach($items as $item): 
        $image = $viewModel->getImageUrlFromItem($item);
        $itemOptions = $item->getProductOptions();
        $attributes = $itemOptions['attributes_info'] ?? [];
        $customOptions = $itemOptions['options'] ?? [];
    ?>
        <li class="order-product">
            <!-- Product Image -->
            <div class="product-thumbnail">
               <img src="<?= $image; ?>" alt="<?= $item->getName(); ?>" />
            </div>
            <!-- Pending Approval Badge -->
            <?php if($status = $viewModel->getModerationStatus($item)): ?>
                <div class="product-moderation-status">
                    <strong><?= $status; ?></strong>
                </div>
            <?php endif; ?>
            <!-- Product Name & Details -->
            <div class="product-details">
                <div class="product-name">
                    <p><?= $item->getName(); ?></p>
                </div>
                <!-- Selected Attributes & custom options -->
                <div class="product-attributes">
                    <?php foreach($attributes as $attribute): ?>
                        <div class="attribute">
                            <strong><?= $attribute['label']; ?>:</strong>
                            <span><?= $attribute['value']; ?></span>
                        </div>
                    <?php endforeach; ?>
                    <?php foreach($customOptions as $option): ?>
                        <div class="attribute custom-option">
                            <strong><?= $option['label']; ?>:</strong>
                            <span><?= $option['value']; ?></span>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <!-- Product Price & Qty -->
            <div class="product-price">
                <div class="price">
                    <strong><?= $viewModel->formatCurrency($item->getBaseRowTotal()); ?></strong>
                </div>
                <div class="unit-price">
                    <span><?= $viewModel->getUnitPrice($item); ?>/<?= __("unit"); ?></span>
                <div>
                <div class="qty-ordered">
                    <strong>QTY:</strong>
                    <span><?= number_format($item->getQtyOrdered(), 0) ?></span>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
</ol>
<!-- Order Totals -->
<div class="order-totals">
    <div class="totals-row totals-row--subtotal">
        <div class="label">
            <strong><?= __("Subtotal") ?></strong>
        </div>
        <div class="value">
            <strong><?= $viewModel->formatCurrency($order->getData("subtotal")); ?></strong>
        </div>
    </div>
    <div class="totals-row totals-row--taxes">
        <div class="label">
            <strong><?= __("Taxes") ?></strong>
        </div>
        <div class="value">
            <strong><?= $viewModel->formatCurrency($order->getData("tax_amount")); ?></strong>
        </div>
    </div>
    <div class="totals-row totals-row--shipping">
        <div class="label">
            <strong><?= __("Shipping") ?></strong>
        </div>
        <div class="value">
            <strong><?= $viewModel->formatCurrency($order->getData("shipping_amount")); ?></strong>
        </div>
    </div>
    <?php if($coupon = $order->getData('coupon_code')): ?>
    <div class="totals-row totals-row--discount">
        <div class="label">
            <strong><?= __("Discount") ?> (<?= $coupon; ?>)</strong>
        </div>
        <div class="value">
            <strong><?= $viewModel->formatCurrency($order->getData("discount_amount")); ?></strong>
        </div>
    </div>
    <?php endif; ?>
    <div class="totals-row totals-row--total">
        <div class="label">
            <strong><?= __("Total") ?></strong>
        </div>
        <div class="value">
            <strong><?= $viewModel->formatCurrency($order->getData("grand_total")); ?></strong>
        </div>
    </div>
</div>
