<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<footer id="site-footer" class="section--sm">
    <div class="container">
        <div class="footer-top-row">
            <div>
                <?php echo $block->getChildHtml('links-left'); ?>
                <div class="footer-logo-row">
                    <?php echo $block->getChildHtml('logo-footer'); ?>
                    <?php echo $block->getChildHtml('social-icons'); ?>
                </div>
            </div>
            <div>
                <?php echo $block->getChildHtml('service'); ?>
                <?php echo $block->getChildHtml('links-right'); ?>
            </div>
        </div>
        <div class="footer-end-row">
            <?php echo $block->getChildHtml('copyright'); ?>
        </div>
    </div>
    <?php echo $block->getChildHtml('footer-extra'); ?>
</footer>
