<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<header id="site-header">
    <div class="container">
        <?php echo $block->getChildHtml('drawer-icon'); ?>
        <?php echo $block->getChildHtml('logo-header'); ?>
        <?php echo $block->getChildHtml('language-changer'); ?>
        <?php echo $block->getChildHtml('account-icon'); ?>
        <?php echo $block->getChildHtml('minicart'); ?>
    </div>
</header>
