<div class="hp-wrapper">
  <section class="hp-spotlight">
    <div class="container">
      <div class="can-overlay"></div>
      <div class="text-block">
        <h1 class="spotlight-title">What's Your <br />Resolution <br />For 2021</h1>
        <div class="img-wrap">
          <img
            srcset="<?php echo $block->getViewFileUrl('images/hp/hero-can@2x.png') ?> 2x,
                    <?php echo $block->getViewFileUrl('images/hp/hero-can.png') ?> 1x"
            src="<?php echo $block->getViewFileUrl('images/hp/hero-can.png') ?>"
            alt="Coke can"
          />
        </div>
        <p>Share it with a loved one on a personalised can.</p>
        <div class="actions">
          <a href="/whats-your-resolution" class="action black-to-white xlg _btn-min-width-30">
            <span>Make your can here</span>
            <i class="ion ion-ios-arrow-round-forward"></i>
          </a>
        </div>
      </div>
      <div class="stars-overlay"></div>
    </div>
  </section>

  <section class="section--sm hp-how-it-works">
    <div class="container--md">
      <header>
        <h2 class="info-title">How It Works</h2>
        <p>Are you open <br>to better?</p>
      </header>
      <section>
        <p>Personalize your coke can <br>and commit...</p>
        <div class="can-row">
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
            <img
              class="icon-img-overlay heart"
              src="<?php echo $block->getViewFileUrl('images/hp/heart@2x.png') ?>"
              alt="Heart"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
        </div>
      </section>
      <section>
        <p>...to something <br />or someone you love.</p>
        <div class="can-row">
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
            <img
              class="icon-img-overlay arrow"
              src="<?php echo $block->getViewFileUrl('images/hp/arrow@2x.png') ?>"
              alt="arrow"
            />
          </div>
        </div>
      </section>
      <section>
        <p>Then send it <br />to them or receive it in 2 days.</p>
        <div class="can-row">
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
          <div class="img-wrap">
            <img
              srcset="<?php echo $block->getViewFileUrl('images/_dev/demo-can@2x.jpg') ?> 2x,
                      <?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?> 1x"
              src="<?php echo $block->getViewFileUrl('images/_dev/demo-can.jpg') ?>"
              alt="Coke can"
            />
          </div>
        </div>
      </section>
      <section>
        <div class="actions">
          <a href="/whats-your-resolution" class="action secondary xlg">Make your can here</a>
        </div>
      </section>
    </div>
  </section>

  <section class="section--md hp-resolutions">
    <div class="container--sm">
      <header>
        <h3 class="sub-title">Resolutions</h3>
        <p>From around the world</p>
      </header>
    </div>
    <div class="resolutions-block-wrap">
      <div class="resolutions-block">
        <div class="img-wrap" style="background-image: url(<?php echo $block->getViewFileUrl('images/hp/mask-group@2x.jpg') ?> )"></div>
        <div class="txt-wrap">
        <p>I promise <br />to do <br />better <br />just for <br />you</p>
        </div>
      </div>
      <div class="resolutions-block">
        <div class="img-wrap" style="background-image: url(<?php echo $block->getViewFileUrl('images/hp/mask-group@2x.jpg') ?> )"></div>
        <div class="txt-wrap">
          <p>You are <br />right, it's <br />time for me <br />to try new <br />things</p>
        </div>
      </div>
    </div>
  </section>
</div>
