<script>
    document.body.classList.add('homepage-kp');
</script>

<div id="hp-katy-perry" class="hp-wrapper">
  <section class="hp-spotlight">
    <div class="container">
      <div class="text-block">
        <h1 class="spotlight-title">Katy Perry <br />Resolution <br />Can</h1>
        <div class="img-wrap">
          <img
            srcset="<?php echo $block->getViewFileUrl('images/hp/coke-zero-can-katy-perry-5@2x.png') ?> 2x,
                    <?php echo $block->getViewFileUrl('images/hp/coke-zero-can-katy-perry-5.png') ?> 1x"
            src="<?php echo $block->getViewFileUrl('images/hp/coke-zero-can-katy-perry-5.png') ?>"
            alt="Coke can"
          />
        </div>
        <div class="actions">
          <a href="/whats-your-resolution" class="action black-to-white xlg _btn-min-width-30">
            <span>Get Katy Perry can here</span>
            <i class="ion ion-ios-arrow-round-forward"></i>
          </a>
          <div class="can-overlay"></div>
        </div>
        <p>When you buy a limited edition Katy Perry can, Coca-Cola will donate 100% of the proceeds to support the work of ONE</p>
      </div>
    </div>
  </section>

  <section class="section--sm hp-how-it-works">
    <div class="container--lg">
      <p class="status">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 23">
          <path stroke="#000" stroke-miterlimit="10" stroke-width="1.602" d="M27.803 7.707h-.369l-2.95-6.062C24.36 1.258 23.869 1 23.5 1H2.107C1.492 1 1 1.516 1 2.16v13.415c0 .645.492 1.16 1.107 1.16h1.106c0 2.451 1.967 4.515 4.303 4.515s4.304-2.064 4.304-4.514h8.606c0 2.45 1.967 4.514 4.304 4.514 2.336 0 4.303-2.064 4.303-4.514h.86c.615 0 1.107-.516 1.107-1.161V11.06c0-1.806-1.475-3.354-3.197-3.354zm-8.73.516V3.709h2.583l2.09 4.514h-4.672z"/>
        </svg>
        <span>Check the status of your existing order <a href="#"><strong>Find my Order</strong></a></span>
      </p>

      <header>
        <h2 class="info-title">This year, let's be<br /> open to better</h2>
        <p>Design your own or commit <br>with Katy Perry's resolution</p>
      </header>

      <section>
        <div class="bubble-wrapper kp-how-it-works">

          <img
            class="icon-img-overlay heart"
            src="<?php echo $block->getViewFileUrl('images/hp/heart@2x.png') ?>"
            alt="Heart"
          />

          <img
            class="icon-img-overlay arrow"
            src="<?php echo $block->getViewFileUrl('images/hp/arrow@2x.png') ?>"
            alt="arrow"
          />

          <h4>How it Works</h4>
          <div class="can-info-row">
            <div class="can-info">
              <img
                class="arrow arrow-1"
                src="<?php echo $block->getViewFileUrl('images/arrow-1.svg') ?>"
                alt="arrow"
              />
              <img
                src="<?php echo $block->getViewFileUrl('images/_dev/CC_OLNB_EN1@2x.png') ?>"
                alt="Coke can"
              />
              <div class="txt-block">
                <div class="num-bubble"><span>1</span></div>
                <p>Pick a resolution and select your flavour</p>
              </div>
            </div>

            <div class="can-info">
              <img
                class="arrow arrow-2"
                src="<?php echo $block->getViewFileUrl('images/arrow-2.svg') ?>"
                alt="arrow"
              />
              <img
                src="<?php echo $block->getViewFileUrl('images/_dev/CC_OLNB_EN1@2x.png') ?>"
                alt="Coke can"
              />
              <div class="txt-block">
                <div class="num-bubble"><span>2</span></div>
                <p>Think of someone you love and make your pledge</p>
              </div>
            </div>

            <div class="can-info">
              <img
                class="arrow arrow-3"
                src="<?php echo $block->getViewFileUrl('images/arrow-3.svg') ?>"
                alt="arrow"
              />
              <img
                src="<?php echo $block->getViewFileUrl('images/_dev/CC_OLNB_EN1@2x.png') ?>"
                alt="Coke can"
              />
              <div class="txt-block">
                <div class="num-bubble"><span>3</span></div>
                <p>Add your name and the name of your loved one for the perfect gift!</p>
              </div>
            </div>
          </div>
          <div class="actions">
            <a href="/whats-your-resolution" class="action secondary xlg">
              <span>Make your can here</span>
              <i class="ion ion-ios-arrow-round-forward"></i>
            </a>
          </div>
        </div>
      </section>

      <section>
        <div class="bubble-wrapper kp-support">
          <div class="img-bg">
            <div class="overlay"></div>
            <div class="can-overlay"></div>
          </div>
          <div class="content">
            <h5>Support ONE when you buy a limited edition Katy Perry ‘Open To Better’ resolution can</h5>
            <div class="actions">
              <a href="/whats-your-resolution" class="action secondary xlg">
                <span>Get your Katy can here</span>
                <i class="ion ion-ios-arrow-round-forward"></i>
              </a>
            </div>
            <p>When you buy a limited edition Katy Perry resolution can, Coca-Cola will donate 100% of proceeds to support the work of ONE.
Only available in participating countries.</p>
          </div>
        </div>
      </section>

    </div>
  </section>
</div>
