<div class="resolution-wrapper">
    <header>
        <div class="page-title-wrapper">
            <h1 class="page-title">WHAT’S YOUR RESOLUTION?</h1>
        </div>
        <p class="_hide-md _hide-lg _hide-xlg _text-color-light">Share it with a loved one</p>
    </header>

    <div class="product-selector-wrapper">
        <h2 class="header-select header-select-can">
            <span>Select Your Can</span>
            <i class="ion ion-ios-arrow-down"></i>
        </h2>
        <div class="choice-slider">
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/test.jpg') ?>"
                        alt=""
                    />
                </div>
            </div>
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/CC_OLNB_EN1@2x.png') ?>"
                        alt=""
                    />
                </div>
            </div>
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/test2.jpg') ?>"
                        alt=""
                    />
                </div>
            </div>
        </div>

        <h2 class="header-select header-select-flavour">Select Your Flavour</h2>
        <div class="choice-nav">
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/test.jpg') ?>"
                        alt=""
                    />
                </div>
                <div class="name">Regular</div>
            </div>
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/CC_OLNB_EN1@2x.png') ?>"
                        alt=""
                    />
                </div>
                <div class="name">Light</div>
            </div>
            <div class="item">
                <div class="img-wrap">
                    <img
                        src="<?php echo $block->getViewFileUrl('images/_dev/test2.jpg') ?>"
                        alt=""
                    />
                </div>
                <div class="name">Zero</div>
            </div>
        </div>
    </div>

    <script>
    require([
        'jquery',
        'slick',
        'domReady!'
    ], function ($) {

        $('.choice-slider').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            centerMode: true,
            dots: false,
            asNavFor: '.choice-nav',
            focusOnSelect: false,
            nextArrow: '<button type="button" class="next"><i class="ion ion ion-ios-arrow-forward"></i></button>',
            prevArrow: '<button type="button" class="prev"><i class="ion ion-ios-arrow-back"></i></button>',
            responsive: [{
                breakpoint: 768,
                settings: {
                    arrows: false,
                    focusOnSelect: false
                }
            }]
        });

        $('.choice-nav').slick({
            slidesToShow: 3,
            slidesToScroll: 3,
            asNavFor: '.choice-slider',
            dots: true,
            focusOnSelect: true,
        });

        $('.choice-slider').on('beforeChange', function(event, slick, currentSlide, nextSlide){
            const elL = $('.choice-slider').find('*[data-slick-index="0"]').prev()
            const elR = $('.choice-slider').find('*[data-slick-index="2"]').next()

            if (currentSlide == 2 && nextSlide == 0) {
                elL.removeClass('force-active')
                elR.addClass('force-active')
            } else if (currentSlide == 0 && nextSlide == 2) {
                elR.removeClass('force-active')
                elL.addClass('force-active')
            } else {
                elL.removeClass('force-active')
                elR.removeClass('force-active')
            }
        });

    });
    </script>

    <footer>
        <p class="header-select">Now...  It’s time to fill it in!</p>
        <div class="actions">
            <a href="#" class="action secondary">
                <span>Let's do it!</span>
                <i class="ion ion-ios-arrow-round-forward"></i>
            </a>
        </div>
    </footer>
</div>
