<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<div id="mobile-search" class="mobile-search" style="display:none;">
    <form id="mobile_search_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <div class="search-field">
            <input id="search-m"
                type="text"
                name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
                placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                role="combobox"
                aria-haspopup="false"
                aria-autocomplete="both"
                autocomplete="off"
                aria-expanded="false"
                data-mage-init='{
                        "quickSearch":{
                            "formSelector":"#mobile_search_form",
                            "destinationSelector":"#mobile_search_autocomplete",
                            "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                            "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"
                    }
                }'/>
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Search')) ?>" aria-label="Search"></button>
        </div>
    </form>
    <div id="mobile_search_autocomplete" class="search-autocomplete"></div>
    <?= $block->getChildHtml() ?>
</div>
