<?php 
/** @var \Magento\Framework\View\Element\Template $block */ 
/** @var \Coke\France\ViewModel\Data $viewModel */ 
$viewModel = $block->getData('viewModel');
$links = $viewModel->getHeaderLinks();
?>

<?php if($links): ?>
<nav>
    <ul>
        <?php foreach($links as $link): ?>
            <li>
                <?php if ($link['dropdown']) : // Dropdown Link ?>
                    <a href="<?= $link['target']; ?>" data-dropdown-link>
                        <span>
                            <?= $link['title']; ?>
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path fill="none" d="M0 0h24v24H0z"/>
                            <path d="M12 13.172l4.95-4.95 1.414 1.414L12 16 5.636 9.636 7.05 8.222z"/>
                        </svg>
                    </a>
                <?php else: // Normal Link ?>
                    <a href="<?= $link['target']; ?>">
                        <span>
                            <?= $link['title']; ?>
                        </span>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
<?php endif; ?>