<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $item = $block->getItem() ?>
<?php $order = $block->getItem()->getOrder(); ?>
<tr>
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="left">
        <span style="font-size: x-small;">
            <?= $block->escapeHtml($block->getSku($item)) ?>
        </span>
    </td>
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="left">
        <span style="font-size: x-small;">
            <?= $block->escapeHtml($item->getName()) ?>
        </span>
    </td>
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="center">
        <span style="font-size: x-small;">
            <?= /* @escapeNotVerified */  $item->getQty() * 1 ?>
        </span>
    </td>
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="right">
        <span style="font-size: x-small;">
            <?= /* @escapeNotVerified */  str_replace('€', '', $item->getOrder()->formatPrice($item->getPriceInclTax()))?>€
        </span>
    </td>r
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="right">
        <span style="font-size: x-small;">
            <?= /* @escapeNotVerified */  str_replace('€', '', $block->getItemPrice($item)); ?>€
        </span>
    </td>
    <td style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="right">
        <span style="font-size: x-small;">
            <?= /* @escapeNotVerified */  sprintf('%s%%', $item->getOrderItem()->getTaxPercent() + 0); ?>
        </span>
    </td>
</tr>
<?php if ($block->getItemOptions()): ?>
    <tr>
        <td colspan="1" align="left"></td>
        <td colspan="5" style="border-color: #d6d6d6; border-style: solid; border-width: 1px;" align="left">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <span style="font-size: x-small;">
            <strong><em><?= /* @escapeNotVerified */  $option['label'] ?>:</em></strong> <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
        </span>
                <br>

            <?php endforeach; ?>
        </td>
    </tr>
<?php  endif; ?>

