<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist">
       <span class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40">
                <g clip-path="url(#a)">
                    <path fill="#000" d="M19.997 40.001A19.995 19.995 0 1 0 5.86 34.146a19.96 19.96 0 0 0 14.137 5.855z"/>
                    <path fill="#fff" d="m19.997 32.193-9.72-9.718a7.644 7.644 0 0 1 9.72-11.719 7.648 7.648 0 0 1 9.718 11.719l-9.718 9.718zm-7.543-11.898 7.543 7.542 7.542-7.543a4.572 4.572 0 0 0 .08-6.532 4.57 4.57 0 0 0-1.504-1.015 4.544 4.544 0 0 0-3.547.044 4.52 4.52 0 0 0-1.468 1.05l-1.104 1.104-1.094-1.099a4.56 4.56 0 0 0-7.531 1.428 4.562 4.562 0 0 0 1.083 5.025v-.005z"/>
                </g>
                <defs>
                    <clipPath id="a"><path fill="#fff" d="M0 0h40v40H0z"/></clipPath>
                </defs>
            </svg>
        </span>
       <span><?= $block->escapeHtml(__('Save my Design')) ?></span>
    </a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
