<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Contact\Block\ContactForm $block
 * @var \Coke\OLNB\ViewModel\ContactConfig $contactViewModel
 */

$contactViewModel = $block->getContactViewModel();
?>

<?php $isRequestForm = in_array($block->getRequest()->getParam('request'), ['name', 'pledge']);?>

<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <?= $block->getBlockHtml('confirm_email.field') ?>
        <?php if ($isRequestForm): ?>

            <?php if ($block->getRequest()->getParam('request') == 'name'): ?>
                <?php $natureOfInquiry = __('Name Request Form') ?>
            <?php elseif ($block->getRequest()->getParam('request') == 'pledge'): ?>
                <?php $natureOfInquiry = __('Pledge Request Form') ?>
            <?php else: ?>
                <?php $natureOfInquiry = __('Order Inquiry') ?>
            <?php endif; ?>

            <input type="hidden" name="nature_of_inquiry" value="<?= $natureOfInquiry ?>">
        <?php else: ?>
            <?= $block->getBlockHtml('nature.of.inquiry.field') ?>
        <?php endif; ?>

        <?php if (!$isRequestForm): ?>
        <?= $block->getBlockHtml('order.confirmation.number.field') ?>
        <?php endif; ?>

        <?php if ($contactViewModel->isTelephoneEnabled()): ?>
            <div class="field telephone">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
                </div>
            </div>
        <?php endif; ?>

        <?php if ($contactViewModel->isDobEnabled()): ?>
            <?= $block->getBlockHtml('dob.fields') ?>
        <?php else: // Generic fields that will validate successfully ?>
            <input type="hidden" name="day" value="01" />
            <input type="hidden" name="month" value="01" />
            <input type="hidden" name="year" value="1900" />
        <?php endif; ?>

        <?php if ($isRequestForm): ?>
            <?= $block->getBlockHtml('contact.resolution.field') ?>
        <?php endif; ?>

        <div class="field comment required">
            <?php if ($isRequestForm): ?>
                <?= $block->getBlockHtml('whitelist.request') ?>
            <?php else: ?>
                <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <?php endif; ?>

            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr($isRequestForm ? __('Submit my suggestion') : __('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml($isRequestForm ? __('Submit my suggestion') : __('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
